//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingAppWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TId { get; set; }
        public long FromAccountNumber { get; set; }
        public long ToAccountNumber { get; set; }
        public string TransactionType { get; set; }
        public int Amount { get; set; }
        public string MaturityInstruction { get; set; }
        public string Remark { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public Customer Customer { get; set; }
        public Customer Customer1 { get; set; }
    }
}
